name: "Azure CI/CD Deployment"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  call-format:
    name: "Code Formatting Compliance Check"
    uses: markstanden/coding-standards/.github/workflows/format.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  call-build:
    needs: "call-format"
    name: "Build Solution"
    uses: markstanden/coding-standards/.github/workflows/build.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  call-unit-tests:
    needs: "call-build"
    name: "Run Unit Tests"
    uses: markstanden/coding-standards/.github/workflows/unit-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  call-integration-tests:
    needs: "call-unit-tests"
    name: "Run Integration Tests"
    uses: markstanden/coding-standards/.github/workflows/integration-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  call-sonarqube:
    needs: "call-integration-tests"
    name: "SonarQube Analysis"
    uses: markstanden/coding-standards/.github/workflows/sonarqube.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      sonar-project-key: "markstanden_rundog"
      sonar-organization: "markstanden"
    secrets: inherit

  staging-swa-deploy:
    needs: "call-sonarqube"
    name: "Deploy Frontend to Azure Static Web App [staging]"
    runs-on: "ubuntu-latest"
    environment: "staging"
    concurrency:
      group: staging-swa-deploy
      cancel-in-progress: true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: "Restore dependencies"
        run: dotnet restore rundog/rundog.csproj

      - name: "Build"
        run: dotnet build rundog/rundog.csproj --no-restore --configuration Release

      - name: "Publish"
        run: dotnet publish rundog/rundog.csproj --no-restore --configuration Release --output ./publish

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "rundog-frontend-staging"
          if-no-files-found: error
          path: ./publish
          retention-days: 30

      - name: "Deploy to Azure Static Web App"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          output_location: ""
          skip_app_build: true
          is_static_export: true
          deployment_environment: "staging"

  call-e2e-tests:
    needs: "staging-swa-deploy"
    name: "Run End-to-End Tests"
    uses: markstanden/coding-standards/.github/workflows/end-to-end-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  production-swa-deploy:
    needs: "call-e2e-tests"
    name: "Deploy Frontend to Azure Static Web App [production]"
    runs-on: "ubuntu-latest"
    environment: "production"
    concurrency:
      group: "production-swa-deploy"
      cancel-in-progress: true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: "Restore dependencies"
        run: dotnet restore rundog/rundog.csproj

      - name: "Build"
        run: dotnet build rundog/rundog.csproj --no-restore --configuration Release

      - name: "Publish"
        run: dotnet publish rundog/rundog.csproj --no-restore --configuration Release --output ./publish

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "rundog-frontend-production"
          if-no-files-found: error
          path: ./publish
          retention-days: 30

      - name: "Deploy to Azure Static Web App"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          output_location: ""
          skip_app_build: true
          is_static_export: true