name: "Azure CI/CD Deployment"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  check-formatting:
    if: false #Skipping whilst testing E2E test stage
    name: "Code Formatting Compliance Check"
    uses: markstanden/coding-standards/.github/workflows/format.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  build-succeeds:
    if: false #Skipping whilst testing E2E test stage
    needs: "check-formatting"
    name: "Build Solution"
    uses: markstanden/coding-standards/.github/workflows/build.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  run-unit-tests:
    if: false #Skipping whilst testing E2E test stage
    needs: "build-succeeds"
    name: "Run Unit Tests"
    uses: markstanden/coding-standards/.github/workflows/unit-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  run-integration-tests:
    if: false #Skipping whilst testing E2E test stage
    needs: "run-unit-tests"
    name: "Run Integration Tests"
    uses: markstanden/coding-standards/.github/workflows/integration-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  run-sonarqube-deep-analysis:
    if: false #Skipping whilst testing E2E test stage
    needs: "run-integration-tests"
    name: "SonarQube Analysis"
    uses: markstanden/coding-standards/.github/workflows/sonarqube.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
    secrets: inherit

  build-frontend-release:
    #needs: "run-sonarqube-deep-analysis"
    name: "Build Frontend Artifact"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: "Restore dependencies"
        run: dotnet restore rundog/rundog.csproj

      - name: "Build"
        run: dotnet build rundog/rundog.csproj --no-restore --configuration Release

      - name: "Publish"
        run: dotnet publish rundog/rundog.csproj --no-restore --configuration Release --output ./publish

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "rundog-frontend"
          if-no-files-found: error
          path: ./publish
          retention-days: 30

  staging-frontend-deploy:
    needs: "build-frontend-release"
    name: "Deploy Frontend to staging"
    runs-on: "ubuntu-latest"
    environment: "staging"
    concurrency:
      group: staging-swa-deploy
      cancel-in-progress: true
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v4
        with:
          name: "rundog-frontend"
          path: ./publish

      - name: "Deploy to Azure Static Web App"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          output_location: ""
          skip_app_build: true
          is_static_export: true
          deployment_environment: "staging"

  run-e2e-tests:
    needs: "staging-frontend-deploy"
    name: "Run End-to-End Tests"
    uses: markstanden/coding-standards/.github/workflows/end-to-end-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      artifact-name: "rundog-frontend"

  production-frontend-deploy:
    needs: "run-e2e-tests"
    name: "Deploy Frontend to production"
    runs-on: "ubuntu-latest"
    environment: "production"
    concurrency:
      group: "production-swa-deploy"
      cancel-in-progress: true
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v4
        with:
          name: "rundog-frontend"
          path: ./publish

      - name: "Deploy to Azure Static Web App"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          output_location: ""
          skip_app_build: true
          is_static_export: true