name: "Azure Deployment [Production]"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true) }}
    runs-on: "ubuntu-latest"
    name: "Deploy Frontend to Azure Static Web App [Production]"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: "Restore dependencies"
        run: dotnet restore rundog/rundog.csproj

      - name: "Build"
        run: dotnet build rundog/rundog.csproj --no-restore --configuration Release

      - name: "Publish"
        run: dotnet publish rundog/rundog.csproj --no-restore --configuration Release --output ./publish

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "rundog-dev-frontend"
          path: ./publish
          retention-days: 30

      - name: "Deploy to Azure Static Web App"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          output_location: ""
          skip_app_build: true
          deployment_environment: "main"
          is_static_export: true
