name: Azure Deployment

on:
  workflow_run:
    workflows: ["Code Quality Pipeline"]
    types:
      - completed
    branches: ["main"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    name: Deploy to Production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore rundog/rundog.csproj

      - name: Build
        run: dotnet build rundog/rundog.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish rundog/rundog.csproj --no-restore --configuration Release --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rundog-app
          path: ./publish
          retention-days: 30

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          output_location: ""
          skip_app_build: true
          deployment_environment: production
