name: "Code Quality Pipeline"

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  call-format:
    name: "Code Formatting Compliance Check"
    uses: markstanden/coding-standards/.github/workflows/format.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  call-build:
    needs: "call-format"
    name: "Build Solution"
    uses: markstanden/coding-standards/.github/workflows/build.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  call-unit-tests:
    needs: "call-build"
    name: "Run Unit Tests"
    uses: markstanden/coding-standards/.github/workflows/unit-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      test-filter: "FullyQualifiedName~Unit.Tests"

  call-sonarqube:
    needs: "call-unit-tests"
    name: "SonarQube Analysis"
    uses: markstanden/coding-standards/.github/workflows/sonarqube.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      sonar-project-key: "markstanden_rundog"
      sonar-organization: "markstanden"
    secrets: inherit