name: "Code Quality Pipeline"

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  check-formatting:
    name: "Code Formatting Compliance Check"
    uses: markstanden/coding-standards/.github/workflows/format.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  build-succeeds:
    needs: "check-formatting"
    name: "Build Solution"
    uses: markstanden/coding-standards/.github/workflows/build.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  run-unit-tests:
    needs: "build-succeeds"
    name: "Run Unit Tests"
    uses: markstanden/coding-standards/.github/workflows/unit-tests.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      test-filter: "FullyQualifiedName~Unit.Tests"

  run-sonarqube-deep-analysis:
    needs: "run-unit-tests"
    name: "SonarQube Analysis"
    uses: markstanden/coding-standards/.github/workflows/sonarqube.yml@main
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
    secrets: inherit