name: "Code Quality Checks"

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check-formatting:
    name: "Code Formatting Compliance Check"
    uses: markstanden/coding-standards/.github/workflows/dotnet-format--solution.yml@a65ce01e012c56e58163c135b129dcb9698fd615
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  build-succeeds:
    needs: "check-formatting"
    name: "Build Solution"
    uses: markstanden/coding-standards/.github/workflows/dotnet-build--solution.yml@a65ce01e012c56e58163c135b129dcb9698fd615
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}

  run-unit-tests:
    needs: "build-succeeds"
    name: "Run Unit Tests"
    uses: markstanden/coding-standards/.github/workflows/dotnet-test--unit-tests.yml@a65ce01e012c56e58163c135b129dcb9698fd615
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      test-filter: "FullyQualifiedName~Unit.Tests"

  run-sonarqube-deep-analysis:
    needs: "run-unit-tests"
    name: "SonarQube Analysis"
    uses: markstanden/coding-standards/.github/workflows/dotnet-sonarqube.yml@a65ce01e012c56e58163c135b129dcb9698fd615
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
