name: "Manual Build Development Infrastructure"

on:
  workflow_dispatch:

jobs:
  build-development-infrastructure:
    name: "Build Development Environment Infrastructure"
    uses: markstanden/coding-standards/.github/workflows/opentofu-build-infrastructure.yml@2b4aa57b65fe2e32e7960aef2d6ec4f87be694dc
    with:
      opentofu-version: ${{ vars.OPENTOFU_VERSION }}
      infrastructure-directory: "./infrastructure"
      environment: "development"
      project-name: "rundog"
      backend-resource-group-name: ${{ vars.BACKEND_RG_DEV }}
      backend-storage-account-name: ${{ vars.BACKEND_STORAGE_ACCOUNT_DEV }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}


