name: "Development Deploy"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment name, used within resources"
        type: string
        required: false
        default: "development"

      debug-output:
        description: "Enable verbose debug output to aid troubleshooting"
        type: boolean
        required: false
        default: false

jobs:
  build-frontend:
    name: "Build Frontend"
    uses: ./.github/workflows/frontend-build.yml
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      node-version: ${{ vars.NODE_VERSION }}

  build-infrastructure:
    name: "Build Dev Infrastructure"
    uses: ./.github/workflows/infra-build.yml
    with:
      environment: ${{ inputs.environment }}
      backend-resource-group-name: ${{ vars.BACKEND_RG_DEV }}
      backend-storage-account-name: ${{ vars.BACKEND_STORAGE_ACCOUNT_DEV }}
      debug-output: ${{ vars.PIPELINE_DEBUG_MODE == 'true' || inputs.debug-output }}
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-dev:
    name: "Deploy to Development"
    needs: [ "build-frontend", "build-infrastructure" ]
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      artifact-name: ${{ needs.build-frontend.outputs.artifact-name }}
      infrastructure-outputs-artifact-name: ${{ needs.build-infrastructure.outputs.artifact-name }}
      debug-output: ${{ vars.PIPELINE_DEBUG_MODE == 'true' || inputs.debug-output }}
