name: "Manual Destroy Development Infrastructure"

on:
  workflow_dispatch:

jobs:
  destroy-development-infrastructure:
    name: "Destroy Dev Environment Infra "
    uses: markstanden/coding-standards/.github/workflows/opentofu-destroy-workspace.yml@ab5f499da58f2e04ee21ec3903b08c1b5e5f033d
    with:
      opentofu-version: ${{ vars.OPENTOFU_VERSION }}
      infrastructure-directory: "./infrastructure"
      environment: "development"
      project-name: "rundog"
      backend-resource-group-name: ${{ vars.BACKEND_RG_DEV }}
      backend-storage-account-name: ${{ vars.BACKEND_STORAGE_ACCOUNT_DEV }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}


