name: "Frontend Deploy"
on:
  workflow_call:
    inputs:
      environment:
        description: "e.g. staging or production"
        type: string
        required: true

      frontend-artifact-name:
        description: "Frontend artifact name"
        type: string
        required: true

      infrastructure-outputs-artifact-name:
        description: "Name of the artifact containing tofu outputs json file"
        type: string
        required: true

      debug-output:
        description: "Enable verbose debug output to aid troubleshooting"
        type: boolean
        required: false
        default: false

    outputs:
      deployment-url:
        description: "Deployed application URL"
        value: ${{ jobs.deploy.outputs.deployment-url }}

jobs:
  deploy:
    name: "Deploy Frontend to ${{ inputs.environment }}"
    uses: markstanden/coding-standards/.github/workflows/azure-swa--deploy-blazor-wasm.yml@3f39ebc399f4bbff90f56493a70e04a5dad42a3a
    with:
      environment: ${{ inputs.environment }}
      frontend-artifact-name: ${{ inputs.frontend-artifact-name }}
      infrastructure-outputs-artifact-name: ${{ inputs.infrastructure-outputs-artifact-name }}
      concurrency-group: "rundog-${{ inputs.environment }}"
      debug-output: ${{ inputs.debug-output }}
