name: "Frontend Build"
on:
  workflow_call:
    inputs:
      dotnet-version:
        description: ".NET SDK version"
        type: string
        required: false
        default: "8.0.x"
      node-version:
        description: "Node.js version"
        type: string
        required: false
        default: "22"
      retention-days:
        type: number
        default: 1
        description: "Artifact retention days"
      web-project-path:
        type: string
        default: "src/Web"
        description: "Path to the web project directory"
      artifact-name:
        type: string
        default: "frontend-build-artifact"
        description: "Name for the build artifact"
    outputs:
      artifact-name:
        description: "Name of the built artifact"
        value: ${{ inputs.artifact-name }}

jobs:
  build:
    uses: markstanden/coding-standards/.github/workflows/dotnet-build--blazor-frontend.yml@main
    permissions:
      contents: read
      actions: write
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
      node-version: ${{ inputs.node-version }}
      web-project-path: ${{ inputs.web-project-path }}
      artifact-name: ${{ inputs.artifact-name }}
      retention-days: ${{ inputs.retention-days }}
