name: "Frontend Deploy"
on:
  workflow_call:
    inputs:
      environment:
        description: "e.g. staging or production"
        type: string
        required: true

      frontend-artifact-name:
        description: "Frontend artifact name"
        type: string
        required: true

      infrastructure-outputs-artifact-name:
        description: "Name of the artifact containing tofu outputs json file"
        type: string
        required: true

    outputs:
      deployment-url:
        description: "Deployed application URL"
        value: ${{ jobs.deploy.outputs.deployment-url }}

jobs:
  deploy:
    name: "Deploy Frontend to ${{ inputs.environment }}"
    uses: markstanden/coding-standards/.github/workflows/azure-swa--deploy-blazor-wasm.yml@main
    with:
      environment: ${{ inputs.environment }}
      frontend-artifact-name: ${{ inputs.artifact-name }}
      infrastructure-outputs-artifact-name: ${{ inputs.infrastructure-outputs-artifact-name }}
      concurrency-group: "rundog-${{ inputs.environment }}"
