name: "Infrastructure Destroy"
on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment (e.g. staging, production)"
        type: string
        required: true

      project-name:
        description: "Project name used in resource naming"
        type: string
        required: false
        default: "rundog"

      backend-resource-group-name:
        description: "Azure resource group containing OpenTofu state storage"
        type: string
        required: true

      backend-storage-account-name:
        description: "Azure storage account name for OpenTofu state"
        type: string
        required: true

      opentofu-version:
        description: "Version of OpenTofu to use for infrastructure operations"
        type: string
        required: false
        default: "1.7.2"

      infrastructure-directory:
        description: "Path to directory containing OpenTofu configuration files"
        type: string
        required: false
        default: "infrastructure"

      backend-container-name:
        description: "Azure storage container name for state files"
        type: string
        required: false
        default: "tfstate"

      retention-days:
        description: "Number of days to retain workflow artifacts"
        type: number
        required: false
        default: 1

    secrets:
      azure-credentials:
        description: "Azure service principal credentials in JSON format"
        required: true

jobs:
  destroy-infrastructure:
    name: "Destroy Infrastructure (${{ inputs.environment }})"
    uses: markstanden/coding-standards/.github/workflows/opentofu-destroy-workspace.yml@2b4aa57b65fe2e32e7960aef2d6ec4f87be694dc
    with:
      opentofu-version: ${{ inputs.opentofu-version }}
      infrastructure-directory: ${{ inputs.infrastructure-directory }}
      environment: ${{ inputs.environment }}
      project-name: ${{ inputs.project-name }}
      backend-resource-group-name: ${{ inputs.backend-resource-group-name }}
      backend-storage-account-name: ${{ inputs.backend-storage-account-name }}
      backend-container-name: ${{ inputs.backend-container-name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.azure-credentials }}
