name: "Infrastructure Build"
on:
  workflow_call:
    inputs:
      environment:
        description: "e.g. staging or production"
        type: string
        required: true
      project-name:
        description: ""
        type: string
        required: false
        default: "rundog"
      artifact-name:
        type: string
        default: "frontend-build-artifact"
        description: "Name for the build artifact"
      backend-resource-group-name:
        required: true
        type: string
      backend-storage-account-name:
        required: true
        type: string
      opentofu-version:
        required: false
        type: string
        default: "1.7.2"
      infrastructure-directory:
        required: false
        type: string
        default: "infrastructure"
      backend-container-name:
        required: false
        type: string
        default: "tfstate"
      retention-days:
        required: false
        type: number
        default: 1
    secrets:
      azure-credentials:
        required: true

jobs:
  build-infrastructure:
    name: "Build Infrastructure (${{ inputs.environment }})"
    uses: markstanden/coding-standards/.github/workflows/opentofu-build-infrastructure.yml@main
    with:
      opentofu-version: ${{ vars.OPENTOFU_VERSION }}
      infrastructure-directory: ${{ infrastructure-directory }}
      output-artifact-name: ${{ inputs.artifact-name }}
      environment: ${{ inputs.environment }}
      project-name: ${{ inputs.project-name }}
      backend-resource-group-name: ${{ inputs.backend-resource-group-name}}
      backend-storage-account-name: ${{ inputs.backend-storage-account-name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.azure-credentials }}


