name: "Infrastructure Build"
on:
  workflow_call:
    inputs:
      environment:
        description: "e.g. staging or production"
        type: string
        required: true
      project-name:
        description: ""
        type: string
        required: false
        default: "rundog"
      backend-resource-group-name:
        required: true
        type: string
      backend-storage-account-name:
        required: true
        type: string
      opentofu-version:
        required: false
        type: string
        default: "1.7.2"
      infrastructure-directory:
        required: false
        type: string
        default: "infrastructure"
      backend-container-name:
        required: false
        type: string
        default: "tfstate"
      retention-days:
        required: false
        type: number
        default: 1
      artifact-prefix:
        type: string
        required: false
        default: "opentofu-outputs"
    secrets:
      azure-credentials:
        required: true
    outputs:
      artifact-name:
        description: "The generated frontend build artifact name"
        value: "${{ inputs.artifact-prefix }}-${{ inputs.project-name }}-${{ inputs.environment }}-${{ github.run_id }}"

jobs:
  build-infrastructure:
    name: "Build Infrastructure (${{ inputs.environment }})"
    uses: markstanden/coding-standards/.github/workflows/opentofu-build-infrastructure.yml@main
    with:
      opentofu-version: ${{ inputs.opentofu-version }}
      infrastructure-directory: ${{ inputs.infrastructure-directory }}
      output-artifact-name: "${{ inputs.artifact-prefix }}-${{ inputs.project-name }}-${{ inputs.environment }}-${{ github.run_id }}"
      environment: ${{ inputs.environment }}
      project-name: ${{ inputs.project-name }}
      backend-resource-group-name: ${{ inputs.backend-resource-group-name}}
      backend-storage-account-name: ${{ inputs.backend-storage-account-name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.azure-credentials }}


