name: "Pull Request Checks"

on:
  workflow_dispatch:

    inputs:
      debug-output:
        description: "Enable verbose debug output to aid troubleshooting"
        type: boolean
        required: false
        default: false

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  codebase-tests:
    uses: ./.github/workflows/repo-test.yml
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      sonar-org: ${{ vars.SONAR_ORGANIZATION }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      debug-output: ${{ vars.PIPELINE_DEBUG_MODE == 'true' || (github.event_name == 'workflow_dispatch' && fromJSON(github.event.inputs.debug-output || 'false')) }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
